### ISSUE TITLE
Gnome 40 compatible

### ISSUE THREAD

**Issue by ChristopheSilva** [wjt/gnome-shell-spotify-artwork-fixer#1]
Not possible to enable this amazing extension on gnome 40, is it possible to port to gnome 40?

Thank you

**Comment by wjt** [comment]
Patches welcome -- it might just be a matter of adjusting `metadata.json`.

**Comment by stuarthayhurst** [comment]
I'll give this a shot and see what I come up with :)

**Comment by stuarthayhurst** [comment]
That was easy, no code changes required. All it needed was `metadata.json` to be updated, seems to work fine.
EDIT: Tested further, not working yet
