### ISSUE TITLE
Not working on Fedora 34

### ISSUE THREAD

**Issue by TheKlavData** [wjt/gnome-shell-spotify-artwork-fixer#7]
I have installed the extension on Fedora 34 Gnome 40.4.0 and it does not work.

I am not sure if you need any further information.

Thanks in advance!

**Comment by stuarthayhurst** [comment]
Can you try `sudo setcap -r /usr/bin/gnome-shell`? This works around an issue where mutter doesn't have the correct permissions on Fedora and a few other distros.

Thanks

**Comment by TheKlavData** [comment]
I tried that yesterday but did not work. Today I logged in and now it is working.

Thank you for developing this extension!

**Comment by stuarthayhurst** [comment]
No problem, glad it sorted itself :)
